[option]
exclude_paths = []
prefix_label = "g"

[rules]
blocking_assignment_in_always_ff = true
case_default = true
enum_with_type = true
for_with_begin = true
function_same_as_system_function = true
function_with_automatic = true
generate_for_with_label = true
generate_if_with_label = true
generate_keyword_forbidden = true
genvar_declaration_in_loop = true
if_with_begin = true
inout_with_tri = true
input_with_var = true
legacy_always = true
level_sensitive_always = false
loop_variable_declaration = true
non_ansi_module = true
non_blocking_assignment_in_always_comb = true
output_with_var = true
parameter_in_package = true
priority_keyword = true
tab_character = true
unique0_keyword = true
unique_keyword = true
wire_reg = true
