[option]
exclude_paths = []
prefix_label = "g"

[rules]
blocking_assignment_in_always_ff = true
case_default = true
enum_with_type = true
multiline_for_begin = true
function_same_as_system_function = true
function_with_automatic = true
generate_for_with_label = true
generate_if_with_label = true
keyword_forbidden_generate = true
genvar_declaration_in_loop = true
multiline_if_begin = true
inout_with_tri = true
input_with_var = true
keyword_forbidden_always = true
level_sensitive_always = false
loop_variable_declaration = true
non_ansi_module = true
non_blocking_assignment_in_always_comb = true
output_with_var = true
parameter_in_package = true
keyword_forbidden_priority = true
tab_character = true
keyword_forbidden_unique0 = true
keyword_forbidden_unique = true
keyword_forbidden_wire_reg = true
